fix(scripts): repo with no language result in crashes;
caused by:
```
language_name = language['name']
                    ~~~~~~~~^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
```