fix: crash when user has repo that he has not contributed to;
caused by:
```
get_data.py, line 114, in get_recently_edited_repo_by_user
    repo_commit_date = repo['defaultBranchRef']['target']['history']['nodes'][0]['committedDate']
                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
```