fix: when repo is newly created and owner is not the user;
e.g user is added as collaborator of a repo

caused by:
repo['defaultBranchRef']['target']

TypeError: 'NoneType' object is not subscriptable